#!/usr/bin/env node
/**
 * Idempotent patches for the native Android project generated by
 * `npx cap add android`. Safe to run after every `npx cap sync`.
 *
 *  - AndroidManifest.xml: AdMob APPLICATION_ID (from src/config/admob.config.js,
 *    the app crashes at launch without it) and landscape-only orientation.
 *  - MainActivity.java: immersive full screen (status/navigation bars hidden).
 *  - styles.xml / colors: dark window + splash background (no white flash).
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import admobConfig, { USE_TEST_ADS } from '../src/config/admob.config.js';

const ROOT = resolve(import.meta.dirname, '..');
const ANDROID = join(ROOT, 'android');
const MAIN = join(ANDROID, 'app', 'src', 'main');
const BG_COLOR = '#07021a';

if (!existsSync(MAIN)) {
  console.error('android/ not found: run `npx cap add android` first.');
  process.exit(1);
}
if (!USE_TEST_ADS && admobConfig.testing) {
  console.error('USE_TEST_ADS is false but PRODUCTION_IDS are placeholders in src/config/admob.config.js.');
  process.exit(1);
}

const capConfig = JSON.parse(readFileSync(join(ROOT, 'capacitor.config.json'), 'utf8'));
const changes = [];

function patch(file, fn) {
  const before = readFileSync(file, 'utf8');
  const after = fn(before);
  if (after !== before) {
    writeFileSync(file, after);
    changes.push(file.replace(`${ROOT}/`, ''));
  }
}

// ---------------------------------------------------------------- manifest
patch(join(MAIN, 'AndroidManifest.xml'), (xml) => {
  const appId = admobConfig.ids.appId;
  const meta = `<meta-data\n            android:name="com.google.android.gms.ads.APPLICATION_ID"\n            android:value="${appId}" />`;
  if (xml.includes('com.google.android.gms.ads.APPLICATION_ID')) {
    xml = xml.replace(/(android:name="com\.google\.android\.gms\.ads\.APPLICATION_ID"\s*android:value=")[^"]*(")/, `$1${appId}$2`);
  } else {
    xml = xml.replace(/(<application[^>]*>)/, `$1\n\n        <!-- AdMob App ID (managed by scripts/configure-android.mjs from admob.config.js) -->\n        ${meta}\n`);
  }

  // Landscape only (both landscape directions follow the device sensor).
  xml = xml.replace(/(<activity\b[^>]*?android:name="\.MainActivity"[^>]*?)(\s*android:screenOrientation="[^"]*")?(\s*android:exported)/, (m, head, _o, tail) => `${head}\n            android:screenOrientation="sensorLandscape"${tail}`);
  return xml;
});

// ------------------------------------------------------------ MainActivity
const pkgPath = capConfig.appId.replace(/\./g, '/');
const activity = join(MAIN, 'java', pkgPath, 'MainActivity.java');
patch(activity, (src) => {
  if (src.includes('enterImmersiveMode')) return src;
  return `package ${capConfig.appId};

import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;
import androidx.core.view.WindowInsetsControllerCompat;
import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {

    @Override
    public void onWindowFocusChanged(boolean hasFocus) {
        super.onWindowFocusChanged(hasFocus);
        // Re-applied every time focus returns (e.g. after a full-screen ad).
        if (hasFocus) enterImmersiveMode();
    }

    /** Full-screen game: hides status and navigation bars; a swipe shows them temporarily. */
    private void enterImmersiveMode() {
        WindowInsetsControllerCompat controller = WindowCompat.getInsetsController(getWindow(), getWindow().getDecorView());
        controller.setSystemBarsBehavior(WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);
        controller.hide(WindowInsetsCompat.Type.systemBars());
    }
}
`;
});

// ------------------------------------------------------------ build.gradle
// Version from package.json (single source of truth) and release signing
// from android/keystore.properties when present (never committed).
patch(join(ANDROID, 'app', 'build.gradle'), (gradle) => {
  if (gradle.includes('neon-dash: release config')) return gradle;
  gradle = gradle.replace(
    "apply plugin: 'com.android.application'\n",
    `apply plugin: 'com.android.application'

// neon-dash: release config (managed by scripts/configure-android.mjs)
def appPackage = new groovy.json.JsonSlurper().parse(rootProject.file('../package.json'))
def (vMajor, vMinor, vPatch) = appPackage.version.tokenize('.').collect { it.replaceAll(/\\D.*$/, '') as int }
def keystorePropertiesFile = rootProject.file('keystore.properties')
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystorePropertiesFile.withInputStream { keystoreProperties.load(it) }
}
`,
  );
  gradle = gradle.replace(/versionCode \d+/, 'versionCode vMajor * 10000 + vMinor * 100 + vPatch');
  gradle = gradle.replace(/versionName "[^"]*"/, 'versionName appPackage.version');
  gradle = gradle.replace(
    '    buildTypes {\n        release {\n',
    `    signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                storeFile rootProject.file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
    }
    buildTypes {
        release {
            if (keystorePropertiesFile.exists()) {
                signingConfig signingConfigs.release
            }
`,
  );
  return gradle;
});

// Debug builds are signed with the committed android/debug.keystore (a
// throw-away key, like Android Studio's): every CI APK has the same
// signature, so a new build installs over the old one and keeps the saves.
patch(join(ANDROID, 'app', 'build.gradle'), (gradle) => {
  if (gradle.includes('neon-dash: debug signing')) return gradle;
  return gradle.replace(
    '    signingConfigs {\n',
    `    signingConfigs {
        // neon-dash: debug signing (managed by scripts/configure-android.mjs)
        if (rootProject.file('debug.keystore').exists()) {
            debug {
                storeFile rootProject.file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }
`,
  );
});

const keystoreExample = join(ANDROID, 'keystore.properties.example');
if (!existsSync(keystoreExample)) {
  writeFileSync(
    keystoreExample,
    `# Copy to keystore.properties (git-ignored) to sign release builds.
# Create the keystore once with:
#   keytool -genkey -v -keystore neondash-release.jks -alias neondash -keyalg RSA -keysize 2048 -validity 10000
storeFile=neondash-release.jks
storePassword=CHANGE_ME
keyAlias=neondash
keyPassword=CHANGE_ME
`,
  );
  changes.push(keystoreExample.replace(`${ROOT}/`, ''));
}

// ----------------------------------------------------------------- styles
const values = join(MAIN, 'res', 'values');
patch(join(values, 'styles.xml'), (xml) => {
  if (!xml.includes('name="android:windowBackground"')) {
    xml = xml.replace(
      /(<style name="AppTheme\.NoActionBar"[^>]*>)/,
      `$1\n        <item name="android:windowBackground">@color/game_background</item>\n        <item name="android:navigationBarColor">@color/game_background</item>`,
    );
  }
  if (!xml.includes('windowSplashScreenBackground')) {
    xml = xml.replace(
      /(<style name="AppTheme\.NoActionBarLaunch"[^>]*>)/,
      `$1\n        <item name="windowSplashScreenBackground">@color/game_background</item>\n        <item name="android:windowBackground">@color/game_background</item>`,
    );
  }
  return xml;
});

const colorsFile = join(values, 'game_colors.xml');
if (!existsSync(colorsFile)) {
  writeFileSync(colorsFile, `<?xml version="1.0" encoding="utf-8"?>\n<resources>\n    <color name="game_background">${BG_COLOR}</color>\n</resources>\n`);
  changes.push(colorsFile.replace(`${ROOT}/`, ''));
}
patch(join(values, 'ic_launcher_background.xml'), (xml) => xml.replace(/(<color name="ic_launcher_background">)[^<]*(<\/color>)/, '$1#1B0840$2'));

console.log(changes.length ? `Android project configured:\n  - ${changes.join('\n  - ')}` : 'Android project already configured.');
console.log(`AdMob App ID: ${admobConfig.ids.appId}${admobConfig.testing ? ' (TEST)' : ''}`);
